# Generated by Django 2.2.4 on 2019-08-16 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landslide_a', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='image',
            field=models.ImageField(upload_to='landslide_a/static/img'),
        ),
    ]
