# Generated by Django 2.2.4 on 2019-08-18 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landslide_a', '0003_auto_20190817_2029'),
    ]

    operations = [
        migrations.CreateModel(
            name='main_block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_block_title', models.TextField(default='enter first block title here')),
                ('first_block_text', models.TextField(default='enter first block text here')),
                ('second_block_title', models.TextField(default='enter second block title here')),
                ('second_block_text', models.TextField(default='enter second block text here')),
            ],
        ),
    ]
