# Generated by Django 2.2.4 on 2019-08-25 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landslide_a', '0004_main_block'),
    ]

    operations = [
        migrations.CreateModel(
            name='outputs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='Write your title here', max_length=100)),
                ('text', models.TextField(default='Write your text here', max_length=10000)),
            ],
        ),
    ]
