# Generated by Django 2.2.4 on 2019-09-02 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landslide_a', '0005_outputs'),
    ]

    operations = [
        migrations.CreateModel(
            name='events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='Write your title here', max_length=100)),
                ('main_text', models.TextField(default='Write your text here', max_length=100)),
                ('date', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='about',
            name='image_about',
            field=models.ImageField(default='landslide_a/static/img/1502775784-80580920_cQVDkIC.jpg', upload_to='landslide_a/static/img'),
        ),
        migrations.AddField(
            model_name='articles',
            name='link_facebook',
            field=models.TextField(default='#'),
        ),
    ]
