# Generated by Django 2.2.4 on 2019-09-02 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landslide_a', '0006_auto_20190902_1952'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='events',
            new_name='event',
        ),
    ]
