# Generated by Django 2.2.4 on 2019-09-03 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landslide_a', '0007_auto_20190902_1956'),
    ]

    operations = [
        migrations.CreateModel(
            name='person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField(default='enter your name please')),
                ('last_name', models.TextField(default='enter your last name please')),
                ('personal_image', models.ImageField(default='landslide_a/static/img/1502775784-80580920_cQVDkIC.jpg', upload_to='landslide_a/static/img')),
                ('email', models.TextField(default='enter your e-mail')),
                ('link_facebook', models.TextField(default='enter link on your facebook page')),
            ],
        ),
    ]
