# Generated by Django 2.2.4 on 2019-09-04 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landslide_a', '0008_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='type_of_event',
            field=models.TextField(default='Write type of your event'),
        ),
    ]
