# Generated by Django 2.2.4 on 2019-09-04 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landslide_a', '0009_event_type_of_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='time',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='main_text',
            field=models.TextField(default='Write your text here', max_length=10000),
        ),
    ]
