# Generated by Django 2.2.4 on 2019-10-31 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landslide_a', '0014_auto_20191020_1121'),
    ]

    operations = [
        migrations.CreateModel(
            name='case_of_study',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='Write your title here', max_length=100)),
                ('main_text', models.TextField(default='Write your text here', max_length=10000)),
                ('title_ua', models.TextField(default='Введіть заголовок', max_length=100)),
                ('main_text_ua', models.TextField(default='Введіть текст', max_length=10000)),
                ('foto_object', models.ImageField(default='landslide_a/static/img/1502775784-80580920_cQVDkIC.jpg', upload_to='landslide_a/static/img')),
                ('date', models.DateField()),
                ('location', models.TextField(default='Write location heres')),
            ],
        ),
        migrations.DeleteModel(
            name='event',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='link_facebook',
            new_name='link_okid',
        ),
        migrations.AddField(
            model_name='person',
            name='current_position',
            field=models.TextField(default='Enter current position here'),
        ),
        migrations.AddField(
            model_name='person',
            name='current_position_ua',
            field=models.TextField(default='Enter current position here'),
        ),
        migrations.AddField(
            model_name='person',
            name='interests',
            field=models.TextField(default='Enter your interests here'),
        ),
        migrations.AddField(
            model_name='person',
            name='interests_ua',
            field=models.TextField(default='Enter your interests here'),
        ),
    ]
