# Generated by Django 2.2.4 on 2019-11-01 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landslide_a', '0015_auto_20191031_1539'),
    ]

    operations = [
        migrations.CreateModel(
            name='geological_background',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='Enter header')),
                ('name_ua', models.TextField(default='Enter header')),
                ('description', models.TextField(default='Enter description of object')),
                ('description_ua', models.TextField(default='Enter description of object')),
                ('geol_image', models.ImageField(default='landslide_a/static/img/1502775784-80580920_cQVDkIC.jpg', upload_to='landslide_a/static/img')),
                ('type', models.TextField(default='Karpaty')),
            ],
        ),
        migrations.CreateModel(
            name='geological_objects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='Enter name of object')),
                ('name_ua', models.TextField(default='Enter name of object')),
                ('x_coord', models.FloatField(default=2.3)),
                ('y_coord', models.FloatField(default=2.3)),
                ('adress', models.TextField(default='Enter adress here')),
                ('adress_ua', models.TextField(default='Enter adress here')),
                ('type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landslide_a.geological_background')),
            ],
        ),
        migrations.CreateModel(
            name='foto_news',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto_header', models.TextField(default='Enter header of foto')),
                ('foto', models.ImageField(default='landslide_a/static/img/1502775784-80580920_cQVDkIC.jpg', upload_to='landslide_a/static/img')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landslide_a.Articles')),
            ],
        ),
    ]
