# Generated by Django 2.2.4 on 2019-11-02 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landslide_a', '0017_auto_20191101_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='geological_objects',
            name='desciption',
            field=models.TextField(default='Enter  here'),
        ),
        migrations.AddField(
            model_name='geological_objects',
            name='desciption_ua',
            field=models.TextField(default='Enter  here'),
        ),
    ]
