# Generated by Django 2.2.4 on 2019-11-02 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landslide_a', '0018_auto_20191102_2100'),
    ]

    operations = [
        migrations.CreateModel(
            name='main_object',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField(default='')),
            ],
        ),
        migrations.AlterField(
            model_name='geological_background',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landslide_a.main_object'),
        ),
        migrations.AlterField(
            model_name='geological_objects',
            name='type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landslide_a.main_object'),
        ),
    ]
