# Generated by Django 2.2.4 on 2019-11-02 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landslide_a', '0019_auto_20191102_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='main_object',
            name='image',
            field=models.ImageField(default='landslide_a/static/img/1502775784-80580920_cQVDkIC.jpg', upload_to='landslide_a/static/img'),
        ),
    ]
