# Generated by Django 2.2.4 on 2019-11-04 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landslide_a', '0021_main_object_type_ua'),
    ]

    operations = [
        migrations.CreateModel(
            name='form_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='name')),
                ('last_name', models.TextField(default='last_name')),
                ('mail', models.TextField(default='e-mail')),
                ('phone', models.IntegerField(default=1)),
            ],
        ),
    ]
