# Generated by Django 2.2.4 on 2019-11-04 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landslide_a', '0022_form_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='form_user',
            new_name='form_user1',
        ),
    ]
